export const navItemsData = [
  {
    navigateRoute: '/dashboard',
    category: 'general',
    selected: true,
    icon: 'home',
    label: 'Dashboard',
  },
  {
    navigateRoute: '',
    category: 'general',
    selected: false,
    icon: 'list',
    label: 'Orders',
    value: 8,
  },
  {
    navigateRoute: '',
    category: 'general',
    selected: false,
    icon: 'label',
    label: 'Products',
  },
  {
    navigateRoute: '',
    category: 'general',
    selected: false,
    icon: 'folder_open',
    label: 'Categories',
  },
  {
    navigateRoute: '',
    category: 'general',
    selected: false,
    icon: 'peoples',
    label: 'Customers',
  },
  {
    navigateRoute: '',
    category: 'general',
    selected: false,
    icon: 'report',
    label: 'Reports',
  },
  {
    navigateRoute: '',
    category: 'general',
    selected: false,
    icon: 'star',
    label: 'Cupons',
  },
  {
    navigateRoute: '',
    category: 'general',
    selected: false,
    icon: 'inbox',
    label: 'Inbox',
  },
  {
    navigateRoute: '',
    category: 'information',
    selected: false,
    icon: 'contact_support',
    label: 'Knowledge Base',
  },
  {
    navigateRoute: '',
    category: 'information',
    selected: false,
    icon: 'bubble_chart',
    label: 'Product Updates',
  },
  {
    navigateRoute: '',
    category: 'setting',
    selected: false,
    icon: 'person_outline',
    label: 'Persanal Settings',
  },
  {
    navigateRoute: '',
    category: 'setting',
    selected: false,
    icon: 'settings',
    label: 'Global Settings',
  },
];
